### ISSUE TITLE
High kernel time caused by profiling middleware

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#4]
Hi,
We discovered that running the workload on kernels newer than 4.4 (Ubuntu 16.04.2 now comes with 4.8) will generate a high kernel CPU utilization. We pinpointed the issue to the profiling middleware that generates CPU and memory usage statistics for every request in the workload, in django-workload/django_workload/middleware.py:
```
def middleware(request):
        …
        mem_before = summed(psutil.Process().memory_maps())
        …
```
This line of code will cause excessive “stat” syscalls on “/dev/zero (deleted)”, generating the high kernel CPU utilization:

`stat("/dev/zero (deleted)", 0x7fffffffc4c0) = -1 ENOENT`

The problem is that the psutil module will read the memory maps of the uWSGI process in “/proc/pid” in order to determine the memory consumption. When psutil reads the memory maps, it checks whether the mapped files exist, causing this “stat” call on “/dev/zero (deleted)”. This behavior comes from this line in psutil in https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py
```
if PY3:
                        path = decode(path)
                    path = path.strip()
                    if (path.endswith(' (deleted)') and not
>>>>>>>>>>                   path_exists_strict(path))
                        path = path[:-10]
```
Would it be a solution to disable profiling completely ? Otherwise, is it necessary to profile every request or would a sample-based profiling be closer to real world usage? Also, in the real deployment, is the profiling done using native Python code or in C extensions? Is psutil a good way to profile memory usage or should we switch to something else?

**Comment by cooperlees** [comment]
I like the sampling idea to start with to up the RPS.

As for another way, we could have another process externally monitoring the memory usage when we're interested in that statistic if it's too expensive for other testing.

**Comment by florinpapa** [comment]
Thank you for the insight, we will experiment with sampling and maybe external monitoring for memory usage and create a PR when we have something promising.

**Comment by suresh-srinivas** [comment]
Just to be clear the high system time is due to a kernel lock in  d_alloc_parallel which is to alleviate parallel pathname lookups. https://lwn.net/Articles/692546/

As Florin mentioned the memory profiling calls the psutil which is checking for an invalid file across all the uWSGI processes 
``path_exists_strict(path))
`https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py`

Even with sampling, the parallel path exists will not go away. I agree if we could have a single external process monitoring that would avoid the contention. It could even be in one of the uWSGI processes.

Until that time, could we disable the cpu and memory profiling middleware? @cooperlees it is a 1 line change in django-workload/django_workload/setting.py, could you help upstreaming it.
`#    django_workload.middleware.memory_cpu_stats_middleware,`

**Comment by EdieM** [comment]
Hello, I actually have disabled that line; I can include that modification in a pull request if you’d like.


-
Senalka McDonald

senalka.mcdonald@intel.com
Intel Corporation

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/22 for this. For issue https://github.com/Instagram/django-workload/issues/5 I will implement sample-based profiling and create a different PR.

**Comment by cooperlees** [comment]
@florinpapa made this configurable.
